version: '3'
services:
  go-template:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - .:/go/src/github.com/yagnik/go-template
    working_dir: /go/src/github.com/yagnik/go-template
