version: '3'
services:
  client:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    volumes:
    - ..:/workspace/client
    working_dir: /workspace/client
    command: tail -f /dev/null
    cap_add:
      - SYS_PTRACE
